# Generated by Django 4.2.4 on 2023-08-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_videogame_description_videogame_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='date',
        )
    ]
