# Generated by Django 4.2.4 on 2023-08-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_collection_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='collections',
        ),
        migrations.AddField(
            model_name='collection',
            name='games',
            field=models.ManyToManyField(to='main_app.videogame'),
        ),
    ]
