# Generated by Django 4.2.4 on 2023-08-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='games',
        ),
        migrations.AddField(
            model_name='videogame',
            name='collections',
            field=models.ManyToManyField(to='main_app.collection'),
        ),
    ]
